### ISSUE TITLE
[Semaphore Integration] Issue 7: Start implementation of main Semaphore contract

### ISSUE THREAD

**Issue by evgongora** [ZencypherSolutions/semaphore-stellar-contracts#19] opened 2024-11-18 20:52 UTC
Semaphore contract is the core of the Semaphore protocol, managing groups and members. It delegates zk-SNARK proof validation to the ISemaphoreVerifier contract.

References:
https://github.com/semaphore-protocol/semaphore/blob/main/packages/contracts/contracts/Semaphore.sol

**Comment by BrunoAmbricca** [comment] 2024-11-21 14:07
I would like to work on this issue

**Comment by Kingsuite** [comment] 2024-11-21 14:11
I'd like to take this issue.

**Comment by khayss** [comment] 2024-11-21 14:14
Could I try solving this?

## My Background and How It Can Be Leveraged
I am an intermediate fullstack developer with expertise in Rust and smart contract development. I’ve worked on privacy protocols and zk-SNARK integrations, making me well-equipped for the Semaphore contract implementation.

## Plan to Tackle This Issue
- Review the Semaphore protocol and Stellar requirements.
- Design the contract for group management and proof validation.
- Implement core functionalities like group creation and updates.
- Write tests and ensure functionality on Stellar.
- Document the contract for future use.

**Comment by akintewe** [comment] 2024-11-21 15:27
Could I take a shot at this?

**Comment by KoxyG** [comment] 2024-11-21 16:41
Hi @evgongora i am koxy. I am a returning contributor to Semaphore from ODHacks #9.

I can help convert this contract to a soroban contract. This was my last contribution. https://github.com/ZencypherSolutions/semaphore-stellar-contracts/pull/14

**Comment by TropicalDog17** [comment] 2024-11-21 17:27
Hi, I have experience in various open source Rust projects.

https://github.com/carbonable-labs/svgenerator/pull/10

https://github.com/paradigmxyz/reth/commits/main/?author=TropicalDog17

https://github.com/foundry-rs/foundry/commits/master/?author=TropicalDog17

I will first review the Incremental Merkle Tree concepts, then I will take some time to learn about the Semaphore protocols, and I will try to draft a PR as soon as possible for reviewer/maintainer to know my progress. I will also try to communicate with reviewer/maintainer to get the needed feedback and to improve on my pull request.

**Comment by ryzen-xp** [comment] 2024-11-21 18:17
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by guha-rahul** [comment] 2024-11-21 21:41
Can I try solving this issue? I have built ECDSA siganture signing and verification so i think i should be able to solve it

**Comment by TropicalDog17** [comment] 2024-11-22 02:39
Can I try solving this issue? I have 2+ years of experience in Rust and Solidity

**Comment by KoxyG** [comment] 2024-11-28 12:42
Hi @evgongora, is it possible to be assigned to this? The issue is still open and the current assignee hasn't submitted a pull request yet.

I have extensive experience in the Stellar ecosystem and can confidently work on this.
Please consider my request.

**Comment by guha-rahul** [comment] 2024-11-28 13:31
Still working on it . Will i need to submit a draft pull request ?

**Comment by evgongora** [comment] 2024-11-29 17:10
Hello @guha-rahul! Correct, let me know what you found so far and what you been able to accomplish :)

**Comment by bitfalt** [comment] 2024-12-02 21:04
Closed by #27

**Closed as completed by bitfalt** 2024-12-02 21:04 UTC
Labels: good first issue, medium, ODHack10
